
### 
GET http://localhost:3333/iconsData/88888888
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiODg4ODg4ODgiLCJpZFVzZXIiOiJaTGRNV3JHVTZwbDgwOWJ4SHZ3Q1MiLCJpYXQiOjE2NTY2ODk2MjF9.h8QqQ1oDnMsDfwDljOn9N6DqcSFFartT0xnf2u57uG4"


###

POST http://localhost:3333/setInfo
Content-Type: application/json

{
  "user": "88888888",
  "info": [{"id":"L5qpgBeLhzk4YX9RBSuHB","type":"shortcut","link":"https://www.duolingo.com/","title":"Duolingo"}]
}

### 

DELETE  http://localhost:3333/setInfo/Charly8888