export { addNewFolder } from './addNewFolder'
export { addNewShortcut } from './addNewShortcut'
export { addNewText } from './addNewText'
export { deleteItem } from './deleteItem'
export { openPortalAndUpdateText } from './openPortalAndUpdateText'
export { setGridFirstTime } from './setGridFirstTime'
